on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        
        with:
          message: 'Hey Contributor! Your Pull Request will be reviewed shortly. Keep contributing!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
